Repository GSG-FC02/Bonappetit, pull requests merged in 2021-04, with the labels that each got.

#2 Create the file structure
  css/style.css
  html/contactUs.html
  html/home.html
  html/inspiration.html
  html/restuarents.html
  images/Rstuarents.png
  images/home.png
  images/inspiration.png
  images/logo.png
  index.html
  js/scripts.js
Labels: Done

#21 Change the file structure
  contactUs/contactUs.css
  contactUs/contactUs.html
  home/home.css
  home/home.html
  home/home.js
  inspiration/inspiration.css
  inspiration/inspiration.html
  inspiration/inspiration.js
  restuarents/restuarents.css
  restuarents/restuarents.html
  restuarents/restuarents.js
Labels: Done

#22 creat folder mainpage
  mainpage/index.css
Labels: Done

#5 Update README.md
  README.md
Labels: Done

#23 Create the footer and navigation bar
  restuarents/restuarents.css
  restuarents/restuarents.html
Labels: Done

#24 The structure of the index page has been written
  images/splashlogo.png
  index.html
Labels: Done

#25 The style of the index page has been writte.
  mainpage/index.css
Labels: awaiting-merging

#26 Update README.md
  README.md
Labels: Done

#28 create CSS section of the contactUs page
  contactUs/contactUs.css
Labels: Done

#29 The structure of the home page has been written
  home/home.css
  home/home.html
Labels: Done

#30 The home page style has been created and making them responsive
  home/home.css
Labels: Done

#27 create the html section of contactUs page
  contactUs/contactUs.html
Labels: Done

#32 adding the CSS code of the inspiration page including the navegationB…
  inspiration/inspiration.css
Labels: Done

#34 Rename the restaurant folder to Culture Recipes
  CultureRecipes/CultureRecipes.css
  CultureRecipes/CultureRecipes.html
  CultureRecipes/CultureRecipes.js
Labels: Done

#39 create the script of culture Recipes
  CultureRecipes/CultureRecipes.js
Labels: Done

#40 The script page was created for home,
  home/home.js
Labels: Done

#41 Update to the structural file
  home/home.html
  index.html
Labels: Done

#42 Create a popup page layout
  home/home.css
Labels: Done

#43 Update the Restaurant section to information about Culture Recipes
  README.md
Labels: Done

#36 update the Restaurant file path on navbar
  CultureRecipes/CultureRecipes.html
Labels: Done

#37 create the structure of Culture Recipes with html
  CultureRecipes/CultureRecipes.html
Labels: Done

#38 create Culture Recipes style with css
  CultureRecipes/CultureRecipes.css
Labels: Done

#46 create the script of culture recipes page
  CultureRecipes/CultureRecipes.css
  CultureRecipes/CultureRecipes.js
Labels: Done

#47 Update link path
  CultureRecipes/CultureRecipes.html
  contactUs/contactUs.html
  home/home.html
  index.html
  inspiration/inspiration.html
Labels: Done

#50 add html of popUp window to the inspiration page
  inspiration/inspiration.html
Labels: Done

#51 add style of popUp window of inspiration page
  inspiration/inspiration.css
Labels: Done

#52 add js code of inspiration page and the popUp window
  inspiration/inspiration.js
Labels: Done

#56 update all files
  CultureRecipes/CultureRecipes.css
  contactUs/contactUs.css
  home/home.css
  home/home.js
  inspiration/inspiration.css
Labels: Done

#58 editing Response
  inspiration/inspiration.css
Labels: awaiting-review
